### ISSUE TITLE
urlparse2 broken at pypi

### ISSUE THREAD

**Issue by aitzol** [mwhooker/urlparse2#1]
Not sure if this is the correct place for this issue (maybe a Pypi issue), but urlparse2 package is broken at pypi

**Comment by glyphobet** [comment]
Broken how? Do you have a traceback?

**Comment by aitzol** [comment]
it's an empty package it only has a EGG-INFO directory
aitzol@arno:/devel/downloads/urlparse2-1.0-py2.7.egg$ ls -l
guztira 1
drwxr-xr-x 2 aitzol aitzol 1024 uzt 18 14:10 EGG-INFO

I have installed using buildout

**Comment by glyphobet** [comment]
OMG you are right. The `setup.py` doesn't include the actual `urlparse1.py` and `urlparse2.py`. Epic troll, @mwhooker.

**Comment by mwhooker** [comment]
thanks for catching this. Fixed and pushed to pypi.
